### ISSUE TITLE
Hello, could you tell me how the project works

### ISSUE THREAD

**Issue by mozai147** [septemhill/single-dpos-pbft#1]
I don't know which command the project should run on. Can you tell me ?
Thank you

**Comment by septemhill** [comment]
@mozai147 
u can build the project by "go build", and can run different computer(s) or in one.
There's a file called "config.json", the file list all forger's ID and serve address:port,

if u want to run on many computers, can execute command as follows:
[computer 1] ./single-dpos-pbft -i 0 -p 10000 
[computer 2] ./single-dpos-pbft -i 1 -p 10000
....
[computer n] ./single-dpos-pbft -i n-1 p 10000

second options, u run many processes on a computer:

[computer process 1] ./single-dpos-pbft -i 0 -p 10000
[computer process 2] ./single-dpos-pbft -i 1 -p 10001
[computer process 3] ./single-dpos-pbft -i 2 -p 10002
...
[computer process n] ./single-dpos-pbft -i n-1 -p 1000n

Oh, remember, update your own config.json

**Comment by mozai147** [comment]
Sorry, I am a Linux beginner, can you give me an example on a computer running on it？

How do I change my config.json file？Thank you
@septemhill

**Comment by septemhill** [comment]
First, if u DO NOT setup golang environment, please build it up
Second, if u done first one, then follow previous reply

In my own config.json, the config ran it background in the same pc with many processes, 
u can follow this method, but update ur IP address

If you IP is 192.168.32.112, then replace to "dest" field, and follow this command:

./single-dpos-pbft -i 0 -p 10000 &
./single-dpos-pbft -i 1 -p 10000 &
./single-dpos-pbft -i 2 -p 10000 &
.....
./single-dpos-pbft -i n -p 1000n &

**Comment by septemhill** [comment]
If no further question, I'll close the issue two day later, thanks
